
package br.com.caelum.fj91.cliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Dicionario", targetNamespace = "http://ws.caelum.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Dicionario {


    /**
     * 
     * @param palavra
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "traducao", targetNamespace = "")
    @RequestWrapper(localName = "traduz", targetNamespace = "http://ws.caelum.com.br/", className = "br.com.caelum.fj91.cliente.Traduz")
    @ResponseWrapper(localName = "traduzResponse", targetNamespace = "http://ws.caelum.com.br/", className = "br.com.caelum.fj91.cliente.TraduzResponse")
    @Action(input = "http://ws.caelum.com.br/Dicionario/traduzRequest", output = "http://ws.caelum.com.br/Dicionario/traduzResponse")
    public String traduz(
        @WebParam(name = "palavra", targetNamespace = "")
        String palavra);

    /**
     * 
     * @param palavra
     * @param traducao
     */
    @WebMethod
    @RequestWrapper(localName = "adicionaTraducao", targetNamespace = "http://ws.caelum.com.br/", className = "br.com.caelum.fj91.cliente.AdicionaTraducao")
    @ResponseWrapper(localName = "adicionaTraducaoResponse", targetNamespace = "http://ws.caelum.com.br/", className = "br.com.caelum.fj91.cliente.AdicionaTraducaoResponse")
    @Action(input = "http://ws.caelum.com.br/Dicionario/adicionaTraducaoRequest", output = "http://ws.caelum.com.br/Dicionario/adicionaTraducaoResponse")
    public void adicionaTraducao(
        @WebParam(name = "palavra", targetNamespace = "")
        String palavra,
        @WebParam(name = "traducao", targetNamespace = "")
        String traducao);

}
